### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Ethan-B123** [Ethan-B123/quickFeeds#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation

**Comment by dobrynin** [comment]
Demo login seems broken :(

**Comment by dobrynin** [comment]
Logout button needs some styling.

**Comment by dobrynin** [comment]
looks good!
