### ISSUE TITLE
PA Review: RSS Feeds

### ISSUE THREAD

**Issue by Ethan-B123** [Ethan-B123/quickFeeds#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by dobrynin** [comment]
New Feed form needs some styling

**Comment by dobrynin** [comment]
👍
